// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Admin_Tools = "Admin Tools",
  Armchair_D = "Armchair D",
  Armchair_D_2 = "Armchair D_2",
  Armchair_D_3 = "Armchair D_3",
  Armchairs_Upstairs = "Armchairs_Upstairs",
  Billboard_Text = "Billboard_Text",
  Building = "Building",
  Coffee_Table = "Coffee Table",
  Coffee_Table_2 = "Coffee Table_2",
  Concrete_Square_Planter_1 = "Concrete Square Planter_1",
  Concrete_Square_Planter_2 = "Concrete Square Planter_2",
  Door_01 = "Door_01",
  Door_01_Trigger = "Door_01_Trigger",
  Door_02 = "Door_02",
  Door_02_Trigger = "Door_02_Trigger",
  Doors = "Doors",
  Flower_crop = "Flower crop",
  Flower_crop_2 = "Flower crop_2",
  Hub = "Hub",
  Image_1 = "Image_1",
  Image_2 = "Image_2",
  Image_3 = "Image_3",
  Image_4 = "Image_4",
  Palm_glb = "Palm.glb",
  Palm_glb_2 = "Palm.glb_2",
  Palm_glb_2_3 = "Palm.glb_2_3",
  Palm_glb_2_3_4 = "Palm.glb_2_3_4",
  Palm_glb_2_3_4_5 = "Palm.glb_2_3_4_5",
  Palms = "Palms",
  Photowall = "Photowall",
  Photowall_Custom_Image = "Photowall_Custom_Image",
  Photowall_Light_01 = "Photowall_Light_01",
  Photowall_Light_02 = "Photowall_Light_02",
  Plant_2 = "Plant 2",
  Plant_2_2 = "Plant 2_2",
  Plant_2_2_3 = "Plant 2_2_3",
  Plant_2_2_3_4 = "Plant 2_2_3_4",
  Plant_2_2_4 = "Plant 2_2_4",
  Plant_2_3 = "Plant 2_3",
  Planted_Fern_1 = "Planted Fern_1",
  Planted_Fern_2 = "Planted Fern_2",
  Planted_Fern_3 = "Planted Fern_3",
  Planted_Fern_4 = "Planted Fern_4",
  Plants_Pots_Back = "Plants_Pots_Back",
  Plants_Pots_Front = "Plants_Pots_Front",
  Streamer_Chair_1 = "Streamer_Chair_1",
  Streamer_Chair_2 = "Streamer_Chair_2",
  Streamer_Set = "Streamer_Set",
  Streamers = "Streamers",
  Video_Screen = "Video Screen",
  VideoScreen___Images = "VideoScreen & Images",
  mic_gltf = "mic.gltf",
  photowall_light_gltf = "photowall_light.gltf",
  photowall_light_gltf_2 = "photowall_light.gltf_2",
} 
